### ISSUE TITLE
Application Plans.

### ISSUE THREAD

**Issue by JohnyMac** [JohnyMac/ExtremeStudio#1]
Task List Before First 0.1 Release: 
- [x] Enhance syntax highlighting to support more sets with a custom simple regex parser.
- [x] Add compiling with ability to select custom includes folder.
- [x] Add Search, Replace, goto and various other IDE fundamentals.
- [x] Add ES plugins system.
- [x] Fix a bug in the SAMP includes and plugins systems.
- [x] Enhance the auto-complete system to show more accurate auto-completes depending on caret 
position. (And also AC paths in #includes and loads of idea.)
- [x] Add CTRL+Click feature.
- [x] Revamp the Object Explorer.
- [x] Revamp the Project Explorer.
- [x] Add Drag n Drop for opening external files.
- [x] Add to be able to create project from existing SAMP files.

Yes that's it for the beta version, I do have tons of ideas to add but since I receive millions of requests to release this ASAP, I will just release it and continue supporting and adding features while its live. :)

*NOTE: The plugins itself like color-picker, ids browser and such will be created as plugins after the beta release.*

**Comment by Ewwe** [comment]
In ExtremePAWN has one bug which i discovered today :) You can only open .pwn file.. Scripters need open .inc too :) So please make sure fix this in ES :)

**Comment by JohnyMac** [comment]
Will be adding it for sure.

For now, enter `*.inc` in the filename text box while opening a file.
And it will allow you to choose .inc files.

An alternative is to just double click the include in the project explorer.

**Comment by JohnyMac** [comment]
I usually keep getting lost and forget what to do next, So I am going to make this my task list which is gonna be updated every time I have new suggestions or finish something.

Task List: 
* Create the plugin system.
* Add the auto-complete system.
* Add tooltips system to show all info about functions in auto-complete and such.
* Add Search and Search & Replace system.
* Add the plugins system for tools.

**Comment by JohnyMac** [comment]
Edited main post with task list.
As soon as I complete this tasks, I'll be happy to release the first version. :D
