### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by matthijsvdmeulen** [JohnyMac/ExtremeStudio#13]
I'm trying to make your portable version truly portable by using a batch file to redirect the %appdata% environment variable to it's own folder, and for some reason this won't work. This is probably something that is easy to fix, and can make your app even more awesome
-Matthijs

**Comment by JohnyMac** [comment]
Yeah, can be done easily instead of changing the %appdata% var which is not recommended cause it will bug other app.
