### ISSUE TITLE
dll and executable

### ISSUE THREAD

**Issue by MOURADD** [JohnyMac/ExtremeStudio#3]
Hi, Can you upload the dll and th executable project 
and thankyou

**Comment by Crayder** [comment]
What dll and what executable project? There are no dlls that need to be packaged, you install them all with the Microsoft redistributables. Also, you create your own projects.

**Comment by MOURADD** [comment]
OK Thanks for help

**Comment by JohnyMac** [comment]
The app hasn't been released yet, build it yourself.
