### ISSUE TITLE
[Suggestion] Invert project folder check

### ISSUE THREAD

**Issue by TopFuel** [JohnyMac/ExtremeStudio#6]
Hello, I want to make a suggestion:
Here on these [lines](https://github.com/JohnyMac/ExtremeStudio/blob/a7c79e99480ed691969361d505cdfb0cafe1ea22/ExtremeCore/Classes%20and%20Modules/generalFunctions.vb#L132-L135) you are checking if the folders exists and if not create them.
But as you're calling the ['IsValidSAMPFolder' function in 'IsValidExtremeProject'](https://github.com/JohnyMac/ExtremeStudio/blob/a7c79e99480ed691969361d505cdfb0cafe1ea22/ExtremeCore/Classes%20and%20Modules/generalFunctions.vb#L124) before checking for the file 'extremeStudio.config' and the folder 'configs', the folders 'gamemodes', 'pawno', 'pawno/include' and 'plugins' are always created, even if an error appears.

So my suggestion is:
Only call 'IsValidSAMPFolder' after checking for the file 'extremeStudio.config' and the folder 'configs', this way it will not create the folders if it is not a ExtremeStudio project.

**Comment by JohnyMac** [comment]
Oh, Thats a bug actually since it creates the folders everytime you choose a folder xD.. I will invert the IsValidSAMPFolder to check for the executables first like the `samp-server.exe`, `announce.exe` and `server.cfg` etc... And then create the folders if not exists.
