### ISSUE TITLE
[Suggestion] Warning and error showing.

### ISSUE THREAD

**Issue by Sanady** [JohnyMac/ExtremeStudio#8]
Hello, you should put warnings and errors together, because people won't change to see warnings and then other page are errors, they want to see all in one page, that's my suggestion, that would be better  :)

**Comment by JohnyMac** [comment]
Umm.. Its already like that, The buttons are toggle ones so if both are toggled/pressed, it will show both. And if you want, You can hide one and show the other by just toggling it to disabled.

**Comment by Crayder** [comment]
@Sanady, ever used Visual Studio?

**Comment by Sanady** [comment]
Why are you asking Crayder, I did once.

**Comment by JohnyMac** [comment]
Because it's similar, it worked ?
